nginx:
  build: images/nginx
  command: nginx -g "daemon off;"
  links:
    - php
  volumes:
    - ./images/php/app/public:/var/www/html/app/public
php:
  build: images/php
  volumes:
    - ./images/php:/var/www/html
  working_dir: /var/www/html/app/public
  command: php-fpm
  links:
    - cache
  environment:
    APP_ENV: local
    APP_DEBUG: 'true'
    APP_KEY: SomeRandomKey!!!
    APP_LOCALE: en
    APP_FALLBACK_LOCALE: en
    TELEGRAM_API: telegramapikey
    TELEGRAM_CHAT_ID: destinationchatid
    MEMCACHED_HOST: cache
    CACHE_DRIVER: memcached
cache:
  image: memcached:1.6-alpine
